[tools]
aws-cli = "latest"
azure-cli = "latest"
gcloud = "latest"
go = "latest"
node = "latest"
"npm:@openai/codex" = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:claude-code-monitor" = "latest"
"npm:gitnexus" = "latest"
"npm:portless" = "latest"
"npm:pyright" = "latest"
pnpm = "latest"
python = "latest"
terraform = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
