[tools]
aws-cli = "latest"
azure-cli = "latest"
gcloud = "latest"
"pipx:headroom-ai" = { version = "latest", extras = "all" }
go = "latest"
node = "latest"
"npm:@openai/codex" = "latest"
"npm:claude-code-monitor" = "latest"
python = "latest"
terraform = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
